### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by connyay** [callawaycloud/apex-rest-route#5]
Hiya,

Nice library! 

Is there a license decided for the repo? The package.json indicates ISC, but a root LICENSE file would clear ambiguity a bit.

the `apex-graphql-query` lib is MIT, so wasn't sure if this one was intended to be as well.

**Comment by ChuckJonas** [comment]
Added MIT.

Sorry bout that!

**Comment by connyay** [comment]
Thanks @ChuckJonas!
